### ISSUE TITLE
Cannot run TableMe executable

### ISSUE THREAD

**Issue by hanliger** [MaxKinny/TabRecSet#2]
Hi MaxKinny,

First of all, great work! I tried to download and run your GUI annotation tool, but when I run .exe file, a console windows appears and then gets closed immediately. Could you help me out with this?

**Comment by MaxKinny** [comment]
We apologize for the inconvenience. Because we are dealing with a copyright application, the complete version is not yet available. Here is a temporary version with one week trial period. Feel free to download it from our data repository: https://doi.org/10.6084/m9.figshare.20647788

**Comment by hanliger** [comment]
No problem, I very much appreciate the trial version. I really hope the copyright issue gets resolved soon. 
Keep up the amazing work. Thanks!

**Comment by MaxKinny** [comment]
> Hi MaxKinny,At the moment, the problem is still there, I still can't run after installing the conda environment according to the steps.Can you help, thank you very much！！

Sorry for the late reply. We have registered the software copyright for TableMe and released its fully functional version.
