### ISSUE TITLE
多边形坐标点

### ISSUE THREAD

**Issue by winterYANGWT** [MaxKinny/TabRecSet#3]
模型只能使用4个点作为标注，可以使用opencv获得的最小外接矩形来代替超过4个点的标注吗？

**Comment by MaxKinny** [comment]
Do you mean detecting the cell bboxes? In the case of all lines, it is possible since the cell borders provide obvious visual clues for the model to learn these features. However, in the case of three lines and no lines, we recommend using the cell-grouped text bboxes from OCR as the annotations.
