### ISSUE TITLE
数据集标注是否有错误？

### ISSUE THREAD

**Issue by winterYANGWT** [MaxKinny/TabRecSet#4]
非常感谢您的工作与付出。但是我发现数据集的一些标注好像有一些问题。以/TSR_TCR_annotation/chinese/_ee35k8x_ljh.json为例，label为“2-1-7-1-眼部检查”的起始列为1，但label为"8-1-1-1-眼底"的起始列也为1。但从图像来看，眼底的起始列应该是眼部检查的后面。这种问题在其他的标注文件中也有出现。且这个数据集中的一些cell的points的标注也是有一些问题的。请问是否是标注出现了一些错误，还是我的理解有一些问题。

**Comment by MaxKinny** [comment]
Thanks for reminding us! The original structure annotation was \<row\>-**\<cell-index\>**-\<rowspan\>-\<colspan\>. We transfer the structure annotation to \<row\>-**\<column\>**-\<rowspan\>-\<colspan\> and update the data repository. Please obtain the latest dataset version from the same download links!

**Comment by zengchan** [comment]
能分享下数据集吗，作者提供的链接下载不了了，十分感谢！

**Comment by MaxKinny** [comment]
> 能分享下数据集吗，作者提供的链接下载不了了，十分感谢！

能正常登上Figshare吗？试试vpn或换个网络。
