### ISSUE TITLE
can't download dataset

### ISSUE THREAD

**Issue by weilx2267** [MaxKinny/TabRecSet#6]
The current DOI URL can not download dataset. Can you update the URL?
Thank you!

**Comment by MaxKinny** [comment]
Did you meet the 403 Forbidden error? I have reported this error to _support@figshare.com_. Hope the office can solve this problem.

**Comment by weilx2267** [comment]
Thank you replay. I download single file, it will show "403 Forbidden". Now Download all , not found any problem. Thank you very much!

**Comment by zengchan** [comment]
> Thank you replay. I download single file, it will show "403 Forbidden". Now Download all , not found any problem. Thank you very much!

May I ask if there are any other download links? Why do I keep downloading 403 Forbidden

**Comment by MaxKinny** [comment]
> > Thank you replay. I download single file, it will show "403 Forbidden". Now Download all , not found any problem. Thank you very much!
> 
> May I ask if there are any other download links? Why do I keep downloading 403 Forbidden

Do you have VPN? Or, other Internet environment?
